name: fj101-runner
# The 'forgejo' network is provided by the Forgejo service.
# Connecting to this network allows communication with the Forgejo service.
networks:
  forgejo:
    name: fj101_forgejo
    external: true
services:
  # Docker-in-Docker daemon to avoid mounting the host docker.sock.
  # This mitigates “full host Docker control” from the runner container.
  dind:
    image: docker:27-dind-rootless
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///run/user/1000/docker.sock
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dind-certs:/certs
      - ./dind-daemon.json:/home/rootless/.config/docker/daemon.json:ro
      # 可選：將數據持久化，防止容器重啟後鏡像和容器丟失
      # - dind-data:/home/rootless/.local/share/docker
    networks:
      forgejo:
        aliases:
          - docker
    hostname: docker

  registry:
    image: registry:2
    restart: always
    networks:
      forgejo:
        aliases:
          - runner-registry
    hostname: runner-registry
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - "127.0.0.1:5000:5000"
  runner:
    image: forgejo-runner-service:9.1.1
    # Runner registration is handled in runner.sh for clarity, not in the command section here.
    command: '/bin/sh -c "sleep 5; forgejo-runner --config /runner-config.yaml daemon"'
    depends_on:
      dind:
        condition: service_healthy
    volumes:
      # Storing persistent data in a local path is preferable to using a named volume, since 'docker compose down -v' will not remove the local directory.
      - ./runner-data:/data
      - ./runner-config.yaml:/runner-config.yaml:ro
      # Mount TLS client certs generated by the DinD service
      - dind-certs:/certs:ro
    environment:
      # Point the runner’s Docker client to the DinD daemon
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - forgejo
volumes:
  dind-certs: