FROM node:22-bookworm

RUN <<EOF
apt-get update 
apt-get install -y jq curl openssl
EOF
# Copy the custom CA certificate into the trusted store directory
# IMPORTANT: The certificate file MUST end with a .crt extension for it to be picked up.
COPY my-ca.crt /usr/local/share/ca-certificates/my-ca.crt

# Update the certificate store
RUN update-ca-certificates