runner:
  insecure: false
  labels:
    - "node22:docker://node:22-bookworm"
    # The DinD container must pull images from the registry
    - "runner100:docker://runner-registry:5000/node22-runner100:latest"